spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: <github-clientid>
            client-secret: <github-clientSecret>
  application:
    name: betterreads-books-app
  main:
    allow-circular-references: true
  data:
    cassandra:
      keyspace-name: books
      username: <userName>
      password: <password>
      schema-action: create-if-not-exists
      request:
        timeout: 10s
      connection:
        connect-timeout: 10s
        init-query-timeout: 10s

datastax.astra: 
    secure-connect-bundle: cassandra-connect.zip

astra.db:
    id: 3fef05fb-a205-4ec9-a0a0-b5ea79e926ff-1
    region: asia-south1
    keyspace: books
    application.token: <token>
 
#  Go to "Manage Organizations --> Token Management" in Astra dashboard (https://astra.datastax.com) and create token to be updated in username, password and application.token parameter.
# Go to Settings --> Developer settings --> Github apps --> create/edit an app --> create user token" in Github to be updated in github clientId and clientSecret. 