spring:
  application:
    name: betterreads-data-loader
  main:
    allow-circular-references: true
  data:
    cassandra:
      keyspace-name: books
      username: dkGkGXlauKISokbkIOajjrJZ
      password: +Ul.U_ac5vx68nisa79zoXDP5krfNtUDjbZCJRnlP-9y-.ez2FCzPZXH_U3YIjLr,PP1cWv5Kde+xMRAZJ6Df9uJ8mrH6MwmgvFHJetrdeHe2q2h1ItO9MgjCcZ5G6dl
      schema-action: create-if-not-exists
      request:
        timeout: 10s
      connection:
        connect-timeout: 10s
        init-query-timeout: 10s

datastax.astra: 
    secure-connect-bundle: cassandra-connect.zip

astra.db:
    id: 3fef05fb-a205-4ec9-a0a0-b5ea79e926ff-1
    region: asia-south1
    keyspace: books
    application.token: AstraCS:dkGkGXlauKISokbkIOajjrJZ:e821204940b3efb7f6991cbfafe7b96adf400e817001662bf373e8c7b842b8b2

datadump.location:
  author: /Users/mohsin/Downloads/authors_dumb.txt
  works: /Users/mohsin/Downloads/works_dumb.txt
